#
# Use this file with the
# - WebStorm Built in Http Client: https://www.jetbrains.com/help/webstorm/http-client-in-product-code-editor.html#graphql
# - VsCode https://marketplace.visualstudio.com/items?itemName=humao.rest-client (this would possibly need some modifications below)
#

###

GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiOWUzOTFmYWYtNjRiMi00ZDRjLWI4NzktNDYzNTMyOTIwZmQ1IiwiZW1haWwiOiJhZG1pbjFAZ21haWwuY29tIiwiaXNBY2Nlc3NUb2tlbiI6dHJ1ZSwiaWF0IjoxNzA4ODEwMzQ3LCJleHAiOjE3MDg4MTIxNDd9.os0Ee9wOvo1JQpCPZBmhScKjsoT-OZKZGZSH7u2S2Ec

query CustomersQuery {
  customers(data: { skip: 0, take: 100 }) {
    id, email, role, activated, activationCode, createdAt, updatedAt
  }
}

###

GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiMDJmNWE0MDktMTAzYi00ZDc1LWI3MjYtOTExMWMwZmUwNWFlIiwiZW1haWwiOiJhZG1pbjJAdGVzdC5jb20iLCJpc0FjY2Vzc1Rva2VuIjp0cnVlLCJpYXQiOjE3MDg3MzQxNzcsImV4cCI6MTcwODczNTk3N30.UjUQCmwmcqMLWsncoIkeQe0fvm-ZitgEUjw2c2kAywA

query CustomerByEmailQuery {
  customer(data: { email: "user@gmail.com" }) {
    id, email, role, createdAt, updatedAt
  }
}

###

GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql

query CustomerByIdQuery {
  customer(data: { id: "9e391faf-64b2-4d4c-b879-463532920fd3" }) {
    id, email, role, createdAt, updatedAt
  }
}

###

GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiOWUzOTFmYWYtNjRiMi00ZDRjLWI4NzktNDYzNTMyOTIwZmQ1IiwiZW1haWwiOiJhZG1pbjFAZ21haWwuY29tIiwiaXNBY2Nlc3NUb2tlbiI6dHJ1ZSwiaWF0IjoxNzA4ODEwMzQ3LCJleHAiOjE3MDg4MTIxNDd9.os0Ee9wOvo1JQpCPZBmhScKjsoT-OZKZGZSH7u2S2Ec

mutation UpdateEmailByCustomerIdMutation {
    updateCustomer(data: { id: "ed6936fc-19d4-4d51-a3ca-e089ea8cab7c", email: "info.johnny@web.de" }) {
    id, email, role, createdAt, updatedAt
  }
}

###

GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiOWUzOTFmYWYtNjRiMi00ZDRjLWI4NzktNDYzNTMyOTIwZmQ1IiwiZW1haWwiOiJhZG1pbjFAZ21haWwuY29tIiwiaXNBY2Nlc3NUb2tlbiI6dHJ1ZSwiaWF0IjoxNzA4ODEwMzQ3LCJleHAiOjE3MDg4MTIxNDd9.os0Ee9wOvo1JQpCPZBmhScKjsoT-OZKZGZSH7u2S2Ec

mutation UpdateRoleByCustomerIdMutation {
    updateCustomer(data: { id: "ed6936fc-19d4-4d51-a3ca-e089ea8cab7c", role: 1 }) {
        id, email, role, createdAt, updatedAt
    }
}

###

GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiOWUzOTFmYWYtNjRiMi00ZDRjLWI4NzktNDYzNTMyOTIwZmQ1IiwiZW1haWwiOiJhZG1pbjFAZ21haWwuY29tIiwiaXNBY2Nlc3NUb2tlbiI6dHJ1ZSwiaWF0IjoxNzA4ODEwMzQ3LCJleHAiOjE3MDg4MTIxNDd9.os0Ee9wOvo1JQpCPZBmhScKjsoT-OZKZGZSH7u2S2Ec

mutation CreateCustomerWithRoleMutation {
    createCustomer(data: { email: "admin2@gmail.com", password: "654321", role: 2 }) {
        id, email, role, createdAt, updatedAt
    }
}

###

GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiOWUzOTFmYWYtNjRiMi00ZDRjLWI4NzktNDYzNTMyOTIwZmQ1IiwiZW1haWwiOiJhZG1pbjFAZ21haWwuY29tIiwiaXNBY2Nlc3NUb2tlbiI6dHJ1ZSwiaWF0IjoxNzA4ODEwMzQ3LCJleHAiOjE3MDg4MTIxNDd9.os0Ee9wOvo1JQpCPZBmhScKjsoT-OZKZGZSH7u2S2Ec

mutation DeleteCustomerMutation {
  deleteCustomer(data: { email: "info.johnny@web.de" }) {
    id, email, role, createdAt, updatedAt
  }
}

###

GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiOWUzOTFmYWYtNjRiMi00ZDRjLWI4NzktNDYzNTMyOTIwZmQ1IiwiZW1haWwiOiJhZG1pbjFAZ21haWwuY29tIiwiaXNBY2Nlc3NUb2tlbiI6dHJ1ZSwiaWF0IjoxNzA4ODEwMzQ3LCJleHAiOjE3MDg4MTIxNDd9.os0Ee9wOvo1JQpCPZBmhScKjsoT-OZKZGZSH7u2S2Ec

mutation DeleteCustomerMutation {
  deleteCustomer(data: { id: "cb962c4d-bd10-4529-a40b-e12b41263aa1" }) {
    id, email, role, createdAt, updatedAt
  }
}

###


GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiOWUzOTFmYWYtNjRiMi00ZDRjLWI4NzktNDYzNTMyOTIwZmQzIiwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsImlzQWNjZXNzVG9rZW4iOnRydWUsImlhdCI6MTcwODgxMDYyMiwiZXhwIjoxNzA4ODEyNDIyfQ.4jLx1iq3Ro5ce1RcL9YHTD_SQASHQBJpE9gzVwhsQJM

mutation ActivateCustomerMutation {
  activateCustomer(data: { email: "user@gmail.com", activationCode: "123456" }) {
    id, email, role, activated, activationCode, createdAt, updatedAt
  }
}

###