#
# Use this file with the
# - WebStorm Built in Http Client: https://www.jetbrains.com/help/webstorm/http-client-in-product-code-editor.html#graphql
# - VsCode https://marketplace.visualstudio.com/items?itemName=humao.rest-client (this would possibly need some modifications below)
#

###

GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiMTEwMzQ3MDMtMThmNS00ZWJiLTk3MDgtZjIwZjc2NDQ2MjA5IiwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsImlzQWNjZXNzVG9rZW4iOnRydWUsImlhdCI6MTcwODczNTA5NCwiZXhwIjoxNzA4NzM2ODk0fQ.Kk1UBLLywB_6mzcCjgbD7Y-d3zc46lF0YjMiBAiLCvE

query CustomersQuery {
  customers(data: { skip: 0, take: 100 }) {
    id, email, role, createdAt, updatedAt
  }
}

###

GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiMDJmNWE0MDktMTAzYi00ZDc1LWI3MjYtOTExMWMwZmUwNWFlIiwiZW1haWwiOiJhZG1pbjJAdGVzdC5jb20iLCJpc0FjY2Vzc1Rva2VuIjp0cnVlLCJpYXQiOjE3MDg3MzQxNzcsImV4cCI6MTcwODczNTk3N30.UjUQCmwmcqMLWsncoIkeQe0fvm-ZitgEUjw2c2kAywA

query CustomerByEmailQuery {
  customer(data: { email: "user@gmail.com" }) {
    id, email, role, createdAt, updatedAt
  }
}

###

GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql

query CustomerByIdQuery {
  customer(data: { id: "9e391faf-64b2-4d4c-b879-463532920fd3" }) {
    id, email, role, createdAt, updatedAt
  }
}

###

GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiMDJmNWE0MDktMTAzYi00ZDc1LWI3MjYtOTExMWMwZmUwNWFlIiwiZW1haWwiOiJhZG1pbjJAdGVzdC5jb20iLCJpc0FjY2Vzc1Rva2VuIjp0cnVlLCJpYXQiOjE3MDg3MzQxNzcsImV4cCI6MTcwODczNTk3N30.UjUQCmwmcqMLWsncoIkeQe0fvm-ZitgEUjw2c2kAywA

mutation UpdateEmailByUserIdMutation {
    updateUser(data: { id:"9e391faf-64b2-4d4c-b879-463532920fd3", email: "user@gmail.com" }) {
    id, email, role, createdAt, updatedAt
  }
}

###

GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql

mutation UpdateRoleByUserIdMutation {
    updateUser(data: { id:"9e391faf-64b2-4d4c-b879-463532920fd3", role: 1 }) {
        id, email, role, createdAt, updatedAt
    }
}

###

GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiMDJmNWE0MDktMTAzYi00ZDc1LWI3MjYtOTExMWMwZmUwNWFlIiwiZW1haWwiOiJhZG1pbjJAdGVzdC5jb20iLCJpc0FjY2Vzc1Rva2VuIjp0cnVlLCJpYXQiOjE3MDg3MzQxNzcsImV4cCI6MTcwODczNTk3N30.UjUQCmwmcqMLWsncoIkeQe0fvm-ZitgEUjw2c2kAywA

mutation CreateUserWithRoleMutation {
    createUser(data: { email: "admin2@test.com", password: "654321", role: 2 }) {
        id, email, role, createdAt, updatedAt
    }
}

###

GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiMTEwMzQ3MDMtMThmNS00ZWJiLTk3MDgtZjIwZjc2NDQ2MjA5IiwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsImlzQWNjZXNzVG9rZW4iOnRydWUsImlhdCI6MTcwODczNTA5NCwiZXhwIjoxNzA4NzM2ODk0fQ.Kk1UBLLywB_6mzcCjgbD7Y-d3zc46lF0YjMiBAiLCvE

mutation DeleteUserMutation {
  deleteUser(data: { email: "test@test.com" }) {
    id, email, role, createdAt, updatedAt
  }
}

###

GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql

mutation DeleteUserMutation {
  deleteUser(data: { id: "d1ff2003-1904-4cb3-9ad3-0eaf51172c77" }) {
    id, email, role, createdAt, updatedAt
  }
}

###
