#
# Use this file with the
# - WebStorm Built in Http Client: https://www.jetbrains.com/help/webstorm/http-client-in-product-code-editor.html#graphql
# - VsCode https://marketplace.visualstudio.com/items?itemName=humao.rest-client (this would possibly need some modifications below)
#

###

GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql

query SignInQuery {
  signIn(data: { email: "admin1@gmail.com", password: "randow-password-admin" }) {
    accessToken,
    refreshToken,
    user {
        id, email, role
    }
  }
}

###

GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql

query SignUpQuery {
    signUp(data: { email: "info.johnny@web.de", password: "test123" }) {
      accessToken,
      refreshToken,
      user {
        id, email, role
      }
    }
}

###

GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql

query RefreshTokenQuery {
  refreshToken(data: { token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiYjJmZTliODUtYTFjYS00YThlLThjY2EtZjllYmNhMmM1ZTVkIiwiZW1haWwiOiJpbmZvLmpvaG5ueUB3ZWIuZGUiLCJpc1JlZnJlc2hUb2tlbiI6dHJ1ZSwiaWF0IjoxNzA4NzM1NjQ4LCJleHAiOjE3MDg4MjIwNDh9.WLxI3Vgqx-PlYRjqGZSgGEYICpvVWRHKcQ5jefFnmVw" }) {
    accessToken,
    refreshToken,
    user {
      id, email, role
    }
  }
}

###
