#
# Use this file with the
# - WebStorm Built in Http Client: https://www.jetbrains.com/help/webstorm/http-client-in-product-code-editor.html#graphql
# - VsCode https://marketplace.visualstudio.com/items?itemName=humao.rest-client (this would possibly need some modifications below)
#

###

GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql

query SignInQuery {
  signIn(data: { email: "admin2@test.com", password: "654321" }) {
    accessToken,
    refreshToken,
    user {
        id, email, role
    }
  }
}

###

GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql

query SignUpQuery {
    signUp(data: { email: "philipp.john@live.de", password: "123456" }) {
      accessToken,
      refreshToken,
      user {
        id, email, role
      }
    }
}

###

GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql

query RefreshTokenQuery {
  refreshToken(data: { token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiMDJmNWE0MDktMTAzYi00ZDc1LWI3MjYtOTExMWMwZmUwNWFlIiwiZW1haWwiOiJhZG1pbjJAdGVzdC5jb20iLCJpc1JlZnJlc2hUb2tlbiI6dHJ1ZSwiaWF0IjoxNzA4NzMxNjA1LCJleHAiOjE3MDg4MTgwMDV9.RmNjkd6OqAKrxh3FBqrOkHoZK7esiLuK6eQ6QaAoq7s" }) {
    accessToken,
    refreshToken,
    user {
      id, email, role
    }
  }
}

###
